Make the scr command consistent with the name of the screen that gets loaded.

diff --git a/default/bin/scr b/default/bin/scr
--- a/default/bin/scr
+++ b/default/bin/scr
@@ -7,9 +7,9 @@ fi
 if [[ "$1" != "" ]]; then
   saved_state=$(stty -g)
 
-  ssh -t "$1" "$SCREEN_CMD -rx gpana_scr" || (failed=$?; tput rmcup; echo "ssh failed with $failed")
+  ssh -t "$1" "$SCREEN_CMD -rx ${USER}_scr" || (failed=$?; tput rmcup; echo "ssh failed with $failed")
   stty -raw
   stty $saved_state
 else
-  $SCREEN_CMD -rx gpana_scr
+  $SCREEN_CMD -rx ${USER}_scr
 fi
