Clean up tabs and indentation.

diff --git a/default/bin/scr b/default/bin/scr
--- a/default/bin/scr
+++ b/default/bin/scr
@@ -5,11 +5,11 @@ if [[ "$SCREEN_CMD" == "" ]]; then
 fi
 
 if [[ "$1" != "" ]]; then
-  saved_state=$(stty -g)
+    saved_state=$(stty -g)
 
-  ssh -t "$1" "$SCREEN_CMD -rx \${USER}_scr" || (failed=$?; tput rmcup; echo "ssh failed with $failed")
-  stty -raw
-  stty $saved_state
+    ssh -t "$1" "$SCREEN_CMD -rx \${USER}_scr" || (failed=$?; tput rmcup; echo "ssh failed with $failed")
+    stty -raw
+    stty $saved_state
 else
-  $SCREEN_CMD -rx ${USER}_scr
+    $SCREEN_CMD -rx ${USER}_scr
 fi
