Pass a verbatim ${USER} in to the ssh command for scr. This means that it will be evaluated on the remote side so that it gets the username used on the remote matchine and not on the local machine.

diff --git a/default/bin/scr b/default/bin/scr
--- a/default/bin/scr
+++ b/default/bin/scr
@@ -7,7 +7,7 @@ fi
 if [[ "$1" != "" ]]; then
   saved_state=$(stty -g)
 
-  ssh -t "$1" "$SCREEN_CMD -rx ${USER}_scr" || (failed=$?; tput rmcup; echo "ssh failed with $failed")
+  ssh -t "$1" "$SCREEN_CMD -rx \${USER}_scr" || (failed=$?; tput rmcup; echo "ssh failed with $failed")
   stty -raw
   stty $saved_state
 else
